# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180923_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
