# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-17 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180918_0121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together=set([]),
        ),
    ]
