# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-17 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0005_auto_20180918_0124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together=set([('content_type', 'object_id', 'valid_period')]),
        ),
    ]
